@TrucoOnline_HostAddress = http://localhost:4000

GET {{TrucoOnline_HostAddress}}/game?lobbyId=27c537d4-f142-436b-867f-b50b17edd458
Accept: application/json


###

POST {{TrucoOnline_HostAddress}}/game/
Accept: application/json

###
