@TrucoOnline_HostAddress = http://localhost:5089

GET {{TrucoOnline_HostAddress}}/game?lobbyId=e0d7a05b-c3ab-40d8-93a4-6e5814c56735
Accept: application/json


###

POST {{TrucoOnline_HostAddress}}/game/
Accept: application/json

###
