@TrucoOnline_HostAddress = http://localhost:5089

GET {{TrucoOnline_HostAddress}}/game?lobbyId=bed16efa-ed2d-4290-80bf-a40822c415e0
Accept: application/json


###

POST {{TrucoOnline_HostAddress}}/game/
Accept: application/json

###
